apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blazingpizza-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: blazingpizza-app
spec:
  source:
    git:
      url: https://github.com/PradeepLoganathan/blazingpizza.git
      ref:
        branch: main